services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend-con
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - petshop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-con
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - petshop-network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-con
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - petshop-network
    depends_on:
      - backend
      - frontend

networks:
  petshop-network:
    driver: bridge