export const BASE_URL = "";
export const USERS_URL = "/api/users";
export const PRODUCTS_URL = "/api/products";
export const DEFAULT_IMAGE = "/images/placeholder.jpg";
export const UPLOADS_URL = "/api/upload";
export const ORDERS_URL = "/api/orders";
export const PAYPAL_URL = "/api/config/paypal";
export const CATEGORY_TYPES = ["toys", "treates", "holidays"];
export const PAGINATION_LIMIT = 3;