---
- name: Configure Petshop App Servers
  hosts: apps
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
          - git
          - awscli
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Clone petshop-devops repository
      ansible.builtin.git:
        repo: https://github.com/bhupendra700/petshop-devops.git
        dest: /home/ubuntu/petshop-devops
        single_branch: yes
        version: main

    - name: Create backend .env from Secrets Manager
      ansible.builtin.shell: |
        aws secretsmanager get-secret-value \
          --secret-id petshop/prod/backend \
          --region us-east-1 \
          --query SecretString \
          --output text | python3 -c '
        import sys, json
        data = json.load(sys.stdin)
        print("\n".join(f"{k}={v}" for k,v in data.items()))
        ' > /home/ubuntu/petshop-devops/backend/.env
      no_log: true

    - name: Create frontend .env
      ansible.builtin.file:
        path: /home/ubuntu/petshop-devops/frontend/.env
        state: touch
        mode: "0644"

    - name: Run application containers
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/petshop-devops
        state: present
        build: always
        recreate: always