---
- name: Configure Petshop MongoDB Server
  hosts: mongodb
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
          - git
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Clone petshop-devops repository
      ansible.builtin.git:
        repo: https://github.com/bhupendra700/petshop-devops.git
        dest: /home/ubuntu/petshop-devops
        single_branch: yes
        version: main

    - name: Run MongoDB container
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/petshop-devops
        files:
          - docker-compose.mongodb.yml
        state: present
        build: always
        recreate: always