# name: Terraform Apply

# on:
#   workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v5

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v5
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#           aws-region: us-east-1

#       - name: Check AWS Identity
#         run: aws sts get-caller-identity

#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v3

#       - name: Terraform Init
#         working-directory: terraform
#         run: terraform init

#       - name: Terraform Apply
#         working-directory: terraform
#         run: terraform apply -auto-approve

#       - name: Install Ansible
#         run: |
#           sudo apt update
#           sudo apt install -y ansible

#           ansible-galaxy collection install amazon.aws
#           ansible-galaxy collection install community.docker

#           /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3 botocore

#       - name: Check Ansible SSM Plugin
#         run: |
#           ansible-doc -t connection amazon.aws.aws_ssm

#       - name: Configure App Servers
#         run: |
#           ansible-playbook \
#             -i ansible/inventory.ini \
#             ansible/configure-project.yml

name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Check AWS Identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_mongodb_atlas_public_key: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
          TF_VAR_mongodb_atlas_private_key: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
          TF_VAR_atlas_project_id: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}
          TF_VAR_mongodb_database_username: ${{ secrets.MONGODB_DATABASE_USERNAME }}
          TF_VAR_mongodb_database_password: ${{ secrets.MONGODB_DATABASE_PASSWORD }}
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

          ansible-galaxy collection install amazon.aws
          ansible-galaxy collection install community.docker

          /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3 botocore

      - name: Check Ansible SSM Plugin
        run: |
          ansible-doc -t connection amazon.aws.aws_ssm

      - name: Check SSM Instances
        run: |
          aws ssm describe-instance-information \
            --output table

      - name: Configure Project
        working-directory: ansible
        run: |
          ansible-playbook \
            -i inventory.ini \
            configure-project.yml
